// Generated by CoffeeScript 1.9.3
(function() {
  var a, arr, b, c, myFunction, obj;

  myFunction = function(arg) {
    if (!arg) {
      alert('false');
    }
    if (!arg) {
      alert('false');
    }
    return true;
  };

  myFunction(false);

  a = 1;

  b = 2;

  c = a === b ? 3 : 4;

  alert(c);

  obj = {
    b: 'c',
    d: 'e'
  };

  arr = [1, 2, 3, 4];

}).call(this);
